name: Build and version package

on:
    pull_request:
        branches: [develop, test, acceptance, main]

permissions:
    contents: write

env:
    NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build (Compile TS)
              run: pnpm build
            - name: Run linter on code (ESLint)
              run: pnpm lint --max-warnings 0
            - name: Check code formatting (Prettier)
              run: pnpm format
            - name: (non-dependabot) Check if declared package version isn't already published
              if: github.actor != 'dependabot[bot]'
              run: pnpm check-version-collision
            - name: (dependabot only) set GIT identity
              if: github.actor == 'dependabot[bot]'
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
            - name: (dependabot only) bump 'patch' version number
              if: github.actor == 'dependabot[bot]'
              run: |
                  git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }} 
                  pnpm version:dependabot
