name: Publish public package to npmjs.com (manual)

on:
    workflow_dispatch:
        inputs:
            totp:
                description: "TOTP (two-factor authentication) code for NPM"
                required: true
                type: number

permissions:
    contents: write
    packages: write

env:
    NPM_TOKEN: ${{ secrets.NPM_PUBLISH }}

jobs:
    publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Set build .npmrc
              run: cp -f .npmrc.build .npmrc
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
                  node-version: ${{ matrix.node-version }}
                  registry-url: "https://registry.npmjs.org"
                  scope: "@nyce"
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Publish (P)NPM package
              run: pnpm publish --access public --no-git-checks --otp ${{ inputs.totp }}
